### ISSUE TITLE
Optimize Fighting

### ISSUE THREAD

**Issue by andreblue** [fpkaliii/dynmusic#1]
https://github.com/fpkaliii/dynmusic/blob/master/lua/autorun/server/sv_dynmusic.lua goes thru all of  the entities in a think hook. Why not  simply  set whom they are fighting in a  damage hook? http://wiki.garrysmod.com/page/GM/EntityTakeDamage is the one i suggest

**Comment by fpkaliii** [comment]
I might use that but one of the things I was aiming for was the music to play if an npc is targetting them even if the player hasn't taken damage yet

**Comment by andreblue** [comment]
Ah,  that makes sense. If only their  was  a hook for NPC's that  ran when they chose an enemy.

**Comment by fpkaliii** [comment]
I'll add support for it anyways, adding in next update.

**Comment by fpkaliii** [comment]
added
